### ISSUE TITLE
chords-and-tabs.net is bugged

### ISSUE THREAD

**Issue by mdesantis** [MinhasKamal/DarkLight#2]
For example: 

* http://www.chords-and-tabs.net/song/name/placebo-36-degrees
* https://minhaskamal.github.io/DarkLight/?url=http://www.chords-and-tabs.net/song/name/placebo-36-degrees

**Comment by MinhasKamal** [comment]
You are accessing a http-page from a https-page. So it may be is happening because- the browser is blocking http request. In Firefox, you can disable the protection, & everything should work fine-
![DarkLight](https://cloud.githubusercontent.com/assets/5456665/23138469/d6b9d3d0-f7d1-11e6-8196-4e126f242d83.png)
